/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analexico;

import java.util.ArrayList;
import analexico.PosFixo;
import javax.swing.JOptionPane;

/**
 *
 * @author Victor
 */
public class AnaLexico extends javax.swing.JFrame {

    
    static String entrada = new String();
    
    static ArrayList<ArrayList<String>> tokenLista = new ArrayList<>();
    
    public AnaLexico() {
        initComponents();
        setLocationRelativeTo(null);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analisador Léxico - VICTOR GUIMARÃES");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Entrada (Código-fonte):");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Saída (Tokens)");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(255, 255, 0));
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTextArea3);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Console:");

        jButton1.setText("Tokens");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Analisar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel3))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1072, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(39, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addComponent(jLabel3)
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(668, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Token tk = new Token();
        if(tokenLista.isEmpty()){
            tk.setVisible(true);
        }else{
            tk.inicia();
            tk.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public ArrayList gerarEntradas(ArrayList entradas, String entrada){
        
        System.out.println("Nova palavra a ser analisada: " + entrada);
        
        entradas.clear();
        
        for(int i = 0; i < entrada.length(); i++){
            if(i != 0)
                entradas.add(entrada.substring(0, i));
            
        }
        
        entradas.add(entrada);
        
        System.out.println("entradas: " + entradas);
        
        return entradas;
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        jTextArea2.setText("");
        jTextArea3.setText("");
        
        entrada = jTextArea1.getText();
        entrada = entrada.trim();
        
        int save = -1, flag = -1;
        
        int retorno = 3;
        
        ArrayList<String> entradas = new ArrayList<>();
        
        entradas = gerarEntradas(entradas, entrada);
        
        int i = 0;
        
        String token = "<ERRO>";
        
        while(entradas.size() > 0){
            while(i < entradas.size()){

                
                for(int j = 0; j < tokenLista.size(); j++){

                    retorno = verifica(entradas.get(i), gerarMatriz(tokenLista.get(j)), 0);


                    if(retorno == 0){
                        flag = j; // Salva posicao j na lista de Tokens
                        save = i; // Salva a posicao i das entradas
                    }

                    

                }
                if(flag != -1){
                    //System.out.println("Palavra " + entradas.get(i) + " reconhecida pelo automato de expressao: " + tokenLista.get(flag).get(0));
                    //JOptionPane.showMessageDialog(null, "Palavra reconhecida pelo automato de expressao: " + tokenLista.get(j).get(0));
                    token = ("<" + tokenLista.get(flag).get(1) + ">");

                }/*else{ 
                    jTextArea2.setText(jTextArea2.getText().concat("<ERRO>"));
                    jTextArea3.setText(jTextArea3.getText().concat("A palavra: \"" + entradas.get(i) + "\" não é reconhecida pela linguagem descrita através das expressões regulares definidas pelo usuário. \n"));
                }   */


                i++;
            }
            
            jTextArea2.setText(jTextArea2.getText().concat(token));
            token = "<ERRO>";
            
            System.out.println("Save: " + save);
            
            if(save != -1){
                System.out.println("Palavra aceita: " + entradas.get(save));
            }else{
                if(entrada.isEmpty()){
                    jTextArea3.setText(jTextArea3.getText().concat("A Palavra vazia não é aceita na linguagem. \n"));
                }else{
                System.out.println("A Palavra: " + entrada.charAt(0) + " não é aceita na linguagem.");
                jTextArea3.setText(jTextArea3.getText().concat("A Palavra: \"" + entrada.charAt(0) + "\" não é aceita na linguagem. \n"));
                }
                
            }
            
            if(save == entradas.size()-1){
                break;
            }else{
                if(save == -1){
                    if(!(entrada.isEmpty())){
                        entrada = entrada.substring(1);
                    }
                    if(!(entrada.isEmpty())){
                        entradas = gerarEntradas(entradas, entrada);
                        save = -1; 
                        flag = -1;
                    }else{
                        break;
                    }
                }else{
                    entrada = entrada.substring(save + 1);
                    entradas = gerarEntradas(entradas, entrada);
                    save = -1; 
                    flag = -1;
                }
                
                
            }
            
            
            
            i = 0;
            
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    public int verifica(String entrada, ArrayList<ArrayList<ArrayList<Integer>>> matriz, int estadoAtual){
        
        if(entrada.length() == 0){
            
            if(matriz.get(estadoAtual).get(0).size() > 1){
                
                return 0;
            }else{
                
                return 1;
            }
            
        }
        
        
        if(PosFixo.alfabeto.indexOf(entrada.charAt(0)) != -1)
            return verifica((entrada.substring(1)), matriz, matriz.get(estadoAtual).get(PosFixo.alfabeto.indexOf(entrada.charAt(0))+1).get(0));
        
        return 1;
    }
    
    
    
    public ArrayList gerarMatriz(ArrayList<String> tokenLista){
        
        ArrayList<ArrayList<ArrayList<Integer>>> matrizAfn = new ArrayList<>();
        ArrayList<ArrayList<ArrayList<Integer>>> matrizAfd = new ArrayList<>();
        
        PosFixo p = new PosFixo();
        Automato a = new Automato();
        
        
        String regex = tokenLista.get(0);
        
        
        regex = p.infixa_para_posfixa(regex);
        regex = regex.replace(" ", "");
        
        
        a.er_para_afn(regex);
        
        matrizAfn = p.criarMatrizAfn(a);
        
        matrizAfd = p.criarMatrizAfd(a.renomeiaMatriz(a.afn_para_afd(matrizAfn)));
        
        System.out.println("AFD: ");
        for(int i = 0; i < matrizAfd.size(); i++){
            for(int j = 0; j < matrizAfd.get(0).size(); j++){
                System.out.print(" " + matrizAfd.get(i).get(j));
            }
            System.out.println("");
        }
        
        return matrizAfd;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaLexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaLexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaLexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaLexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaLexico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
